# Generated by Django 5.2.12 on 2026-03-28 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
